name: djudjo_scheduler
description: DjudjoInk - mobile app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    sqflite: ^2.3.0
    provider: ^6.1.1
    path_provider: ^2.1.1
    intl: ^0.18.1
    shared_preferences: ^2.2.2
    url_launcher: ^6.2.1
    get_it: ^7.6.4
    http: ^1.1.0
    flutter_secure_storage: ^9.0.0
    firebase_core: ^2.22.0
    firebase_crashlytics: ^3.4.8
    flutter_spinkit: ^5.2.0
    flutter_custom_clippers: ^2.1.0
    firebase_auth: ^4.13.0
    cloud_firestore: ^4.13.0
    time_range: ^1.1.0
    syncfusion_flutter_datepicker: ^24.2.7
    mask_text_input_formatter: ^2.6.0
    grouped_list: ^5.1.2
    group_radio_button: ^1.3.0
    flutter_slidable: ^3.0.1
    msh_checkbox: ^2.0.1
    liquid_pull_to_refresh: ^3.0.1
    package_info_plus: ^5.0.1
    awesome_snackbar_content: ^0.1.3
    device_info_plus: ^9.1.1
    dio: ^5.4.0
    image_picker: ^1.0.6
    firebase_storage: ^11.6.0


dependency_overrides:


dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
      - assets/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Raleway
          fonts:
              - asset: fonts/Raleway/Raleway-BlackItalic.ttf
                style: italic
                weight: 900
              - asset: fonts/Raleway/Raleway-BoldItalic.ttf
                style: italic
                weight: 700
              - asset: fonts/Raleway/Raleway-ExtraBoldItalic.ttf
                style: italic
                weight: 800
              - asset: fonts/Raleway/Raleway-ExtraLightItalic.ttf
                style: italic
                weight: 200
              - asset: fonts/Raleway/Raleway-Italic.ttf
                style: italic
              - asset: fonts/Raleway/Raleway-LightItalic.ttf
                style: italic
                weight: 300
              - asset: fonts/Raleway/Raleway-MediumItalic.ttf
                style: italic
                weight: 500
              - asset: fonts/Raleway/Raleway-SemiBoldItalic.ttf
                style: italic
                weight: 600
              - asset: fonts/Raleway/Raleway-ThinItalic.ttf
                style: italic
                weight: 100
              - asset: fonts/Raleway/Raleway-Black.ttf
                weight: 900
              - asset: fonts/Raleway/Raleway-Bold.ttf
                weight: 700
              - asset: fonts/Raleway/Raleway-ExtraBold.ttf
                weight: 800
              - asset: fonts/Raleway/Raleway-ExtraLight.ttf
                weight: 200
              - asset: fonts/Raleway/Raleway-Light.ttf
                weight: 300
              - asset: fonts/Raleway/Raleway-Medium.ttf
                weight: 500
              - asset: fonts/Raleway/Raleway-Regular.ttf
                weight: 400
              - asset: fonts/Raleway/Raleway-SemiBold.ttf
                weight: 600
              - asset: fonts/Raleway/Raleway-Thin.ttf
                weight: 100
        - family: Poppins
          fonts:
              - asset: fonts/Poppins/Poppins-Black.ttf
                weight: 900
              - asset: fonts/Poppins/Poppins-Bold.ttf
                weight: 700
              - asset: fonts/Poppins/Poppins-ExtraBold.ttf
                weight: 800
              - asset: fonts/Poppins/Poppins-SemiBold.ttf
                weight: 600
              - asset: fonts/Poppins/Poppins-Medium.ttf
                weight: 500
              - asset: fonts/Poppins/Poppins-Regular.ttf
                weight: 400
              - asset: fonts/Poppins/Poppins-Light.ttf
                weight: 200
              - asset: fonts/Poppins/Poppins-ExtraLight.ttf
                weight: 100
